development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: orikishi_development
  pool:     5
  username: orikishi
  password: orikishi
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: orikishi_test
  pool:     5
  username: orikishi
  password: orikishi
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: orikishi_production
  pool:     5
  username: orikishi
  password: orikishi
  template: template0
